receivers:
  otlp:
    protocols:
      grpc:
        endpoint: a-dl-tsfo-ka02:4317

exporters:
  loki:
    endpoint: http://a-dl-tsfo-ka02:3100/loki/api/v1/push

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [loki]
