// collector/main.go
package main

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"log"
	"net"
	"os"
	"os/signal"
	"sync"
	"time"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/observability-platform/ebpf-collector/collector/processors"
	"golang.org/x/sys/unix"
)

// Event mirrors the C struct event layout (probes.bpf.c).
// C struct size: 208 bytes. Layout verified by _Static_assert in probes.bpf.c.
type Event struct {
	Type        uint8
	Pad0        [3]byte // matches C: _pad[3]
	Pid         uint32
	Tgid        uint32
	Uid         uint32
	Gid         uint32
	Pad1        uint32 // matches C: _pad1 (aligns timestamp_ns to 8 bytes)
	TimestampNs uint64
	Comm        [16]byte
	Filename    [128]byte
	Saddr       uint32
	Daddr       uint32
	Sport       uint16
	Dport       uint16
	Pad2        uint32 // matches C: _pad2 (aligns latency_ns to 8 bytes)
	LatencyNs   uint64
	Bytes       uint32
	Pad3        uint32 // matches C: _pad3 (aligns struct to 8 bytes)
}

// ConnEvent mirrors the C struct conn_event layout (probes.bpf.c).
// Offsets: type(1)+role(1)+pad(2)+pid(4)=8 | sock_id(8) | ts_ns(8)
//
//	saddr(4)+daddr(4)+sport(2)+dport(2)+pad2(4)=16 | comm(16)
//
// Total: 56 bytes. Layout verified by _Static_assert in probes.bpf.c.
type ConnEvent struct {
	Type   uint8
	Role   uint8
	Pad0   [2]byte
	Pid    uint32
	SockID uint64
	TsNs   uint64
	Saddr  uint32
	Daddr  uint32
	Sport  uint16
	Dport  uint16
	Pad1   [4]byte
	Comm   [16]byte
}

const (
	EventProcess = 1
	EventConnect = 2
	EventLatency = 3
	// EventTcpOpen and EventTcpClose are defined in processors/traces.go
)

var (
	logProc   *processors.LogProcessor
	traceProc *processors.TraceProcessor
)

// bootTimeNs is the wall-clock time of system boot in nanoseconds since Unix epoch.
// bpf_ktime_get_ns() returns nanoseconds since boot (monotonic), so adding this
// offset converts a BPF timestamp to wall-clock time.
var bootTimeNs uint64

func init() {
	var ts unix.Timespec
	if err := unix.ClockGettime(unix.CLOCK_MONOTONIC, &ts); err == nil {
		monotonicNs := uint64(ts.Sec)*1_000_000_000 + uint64(ts.Nsec)
		bootTimeNs = uint64(time.Now().UnixNano()) - monotonicNs
	}
}

// bpf2go compiles probes.bpf.c for each target and generates Go bindings with
// matching build constraints.  -D__TARGET_ARCH_xxx is injected automatically
// by bpf2go per target, so it must not be set here.
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -cflags "-g -O2 -Wno-missing-declarations" -target amd64,arm64 probes ../probes/probes.bpf.c -- -I../probes

func main() {
	// Remove memlock limit — required for BPF maps on older kernels
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatalf("remove memlock: %v", err)
	}

	ctx := context.Background()

	// Initialise processors
	var logShutdown func(context.Context) error
	var err error
	logProc, logShutdown, err = processors.NewLogProcessor(ctx)
	if err != nil {
		log.Fatalf("init log processor: %v", err)
	}
	defer logShutdown(ctx)

	var traceShutdown func(context.Context) error
	traceProc, traceShutdown, err = processors.NewTraceProcessor(ctx)
	if err != nil {
		log.Fatalf("init trace processor: %v", err)
	}
	defer traceShutdown(ctx)

	// Load pre-compiled BPF object (generated by bpf2go)
	objs := probesObjects{}
	if err := loadProbesObjects(&objs, nil); err != nil {
		log.Fatalf("load BPF objects: %v", err)
	}
	defer objs.Close()

	// Attach tracepoint: process execution
	tpExecve, err := link.Tracepoint("syscalls", "sys_enter_execve", objs.TraceExecve, nil)
	if err != nil {
		log.Fatalf("attach execve tracepoint: %v", err)
	}
	defer tpExecve.Close()

	// Attach fentry: TCP active open (client connect)
	feTcpConnect, err := link.AttachTracing(link.TracingOptions{
		Program: objs.TraceTcpConnect,
	})
	if err != nil {
		log.Fatalf("attach tcp_connect fentry: %v", err)
	}
	defer feTcpConnect.Close()

	// Attach fentry: TCP close (both client and server)
	feTcpClose, err := link.AttachTracing(link.TracingOptions{
		Program: objs.TraceTcpClose,
	})
	if err != nil {
		log.Fatalf("attach tcp_close fentry: %v", err)
	}
	defer feTcpClose.Close()

	// Attach fentry/fexit: TCP send/recv latency
	feTcpSend, err := link.AttachTracing(link.TracingOptions{
		Program: objs.TraceTcpSendmsgEnter,
	})
	if err != nil {
		log.Fatalf("attach tcp_sendmsg fentry: %v", err)
	}
	defer feTcpSend.Close()

	feTcpRecv, err := link.AttachTracing(link.TracingOptions{
		Program: objs.TraceTcpRecvmsgExit,
	})
	if err != nil {
		log.Fatalf("attach tcp_recvmsg fexit: %v", err)
	}
	defer feTcpRecv.Close()

	// Attach tracepoint: TCP passive open (server accept via inet_sock_set_state)
	tpSockState, err := link.Tracepoint("sock", "inet_sock_set_state", objs.TraceInetSockSetState, nil)
	if err != nil {
		log.Fatalf("attach inet_sock_set_state tracepoint: %v", err)
	}
	defer tpSockState.Close()

	// Open ring buffer readers
	execRd, err := ringbuf.NewReader(objs.ExecEvents)
	if err != nil {
		log.Fatalf("open exec ring buffer: %v", err)
	}
	dataRd, err := ringbuf.NewReader(objs.DataEvents)
	if err != nil {
		log.Fatalf("open data ring buffer: %v", err)
	}
	connRd, err := ringbuf.NewReader(objs.ConnEvents)
	if err != nil {
		log.Fatalf("open conn ring buffer: %v", err)
	}

	log.Println("collector running — ctrl+c to stop")

	// Graceful shutdown: close all readers so goroutines unblock
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, os.Interrupt)
	go func() {
		<-sig
		execRd.Close()
		dataRd.Close()
		connRd.Close()
	}()

	var wg sync.WaitGroup
	wg.Add(3)

	// Goroutine 1: exec events (process execution logs)
	go func() {
		defer wg.Done()
		var e Event
		for {
			record, err := execRd.Read()
			if err != nil {
				if errors.Is(err, ringbuf.ErrClosed) {
					return
				}
				log.Printf("exec ring buffer read error: %v", err)
				continue
			}
			if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &e); err != nil {
				log.Printf("exec decode error: %v", err)
				continue
			}
			handleProcess(&e)
		}
	}()

	// Goroutine 2: data events (connect + latency)
	go func() {
		defer wg.Done()
		var e Event
		for {
			record, err := dataRd.Read()
			if err != nil {
				if errors.Is(err, ringbuf.ErrClosed) {
					return
				}
				log.Printf("data ring buffer read error: %v", err)
				continue
			}
			if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &e); err != nil {
				log.Printf("data decode error: %v", err)
				continue
			}
			switch e.Type {
			case EventConnect:
				handleConnect(&e)
			case EventLatency:
				handleLatency(&e)
			}
		}
	}()

	// Goroutine 3: conn events (TCP connection lifecycle → trace spans)
	go func() {
		defer wg.Done()
		var e ConnEvent
		for {
			record, err := connRd.Read()
			if err != nil {
				if errors.Is(err, ringbuf.ErrClosed) {
					return
				}
				log.Printf("conn ring buffer read error: %v", err)
				continue
			}
			if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &e); err != nil {
				log.Printf("conn decode error: %v", err)
				continue
			}
			handleConn(&e)
		}
	}()

	wg.Wait()
}

func handleProcess(e *Event) {
	meta := enrich(e.Pid)
	// Convert BPF monotonic timestamp to wall-clock time by adding boot offset.
	wallClockNs := bootTimeNs + e.TimestampNs
	logProc.ProcessExec(context.Background(), processors.ExecEvent{
		Pid:         e.Pid,
		Uid:         e.Uid,
		Gid:         e.Gid,
		TimestampNs: wallClockNs,
		Comm:        nullStr(e.Comm[:]),
		Filename:    nullStr(e.Filename[:]),
		ContainerID: meta.ContainerID,
	})
}

func handleConnect(e *Event) {
	src := net.IP(int32ToBytes(e.Saddr))
	dst := net.IP(int32ToBytes(e.Daddr))
	meta := enrich(e.Pid)
	fmt.Printf("[CONN] pid=%-6d comm=%-16s %s:%d → %s:%d container=%s\n",
		e.Pid, nullStr(e.Comm[:]), src, e.Sport, dst, e.Dport, meta.ContainerID)
}

func handleLatency(e *Event) {
	src := net.IP(int32ToBytes(e.Saddr))
	dst := net.IP(int32ToBytes(e.Daddr))
	latencyMs := float64(e.LatencyNs) / 1_000_000.0
	fmt.Printf("[LAT]  pid=%-6d comm=%-16s %s:%d → %s:%d latency=%.3fms bytes=%d\n",
		e.Pid, nullStr(e.Comm[:]), src, e.Sport, dst, e.Dport, latencyMs, e.Bytes)
	// TODO: emit as OTLP histogram via MetricProcessor
}

func handleConn(e *ConnEvent) {
	wallClockNs := bootTimeNs + e.TsNs
	te := &processors.TcpConnEvent{
		Type:    e.Type,
		Role:    e.Role,
		Pid:     e.Pid,
		SockID:  e.SockID,
		TsNs:    wallClockNs,
		SrcIP:   ipStr(e.Saddr),
		DstIP:   ipStr(e.Daddr),
		SrcPort: e.Sport,
		DstPort: e.Dport,
		Comm:    nullStr(e.Comm[:]),
	}
	traceProc.Handle(context.Background(), te)
}

// ProcMeta holds /proc-derived enrichment data
type ProcMeta struct {
	ContainerID string
	Cmdline     string
	CgroupPath  string
}

// enrich reads /proc/<pid>/cgroup to extract container ID
func enrich(pid uint32) ProcMeta {
	data, err := os.ReadFile(fmt.Sprintf("/proc/%d/cgroup", pid))
	if err != nil {
		return ProcMeta{}
	}
	// Container ID is typically the last 64-char hex segment of the cgroup path
	// Production: parse properly; this is illustrative
	return ProcMeta{CgroupPath: string(data)}
}

func nullStr(b []byte) string {
	n := bytes.IndexByte(b, 0)
	if n < 0 {
		return string(b)
	}
	return string(b[:n])
}

// ipStr converts a uint32 address (stored as little-endian bytes representing
// network-order bytes) into a dotted-decimal string.
// The BPF probe stores skc_rcv_saddr (__be32) directly — the 4 bytes are in
// network order in memory.  binary.LittleEndian.Uint32 reverses them relative
// to network order, so we extract bytes in reverse to get back A.B.C.D.
func ipStr(n uint32) string {
	return net.IP(int32ToBytes(n)).String()
}

func int32ToBytes(n uint32) []byte {
	b := make([]byte, 4)
	binary.LittleEndian.PutUint32(b, n)
	return b
}
