// collector/main.go
package main

import (
    "bytes"
    "encoding/binary"
    "fmt"
    "log"
    "net"
    "os"
    "os/signal"

    "github.com/cilium/ebpf/link"
    "github.com/cilium/ebpf/ringbuf"
    "github.com/cilium/ebpf/rlimit"
)

// Must match the C struct layout exactly (packed, same field order)
type Event struct {
    Type        uint8
    _           [3]byte // padding to align uint32
    Pid         uint32
    Tgid        uint32
    TimestampNs uint64
    Comm        [16]byte
    Filename    [128]byte
    Saddr       uint32
    Daddr       uint32
    Sport       uint16
    Dport       uint16
    LatencyNs   uint64
    Bytes       uint32
    _pad2       uint32 // align struct to 8-byte boundary
}

const (
    EventProcess = 1
    EventConnect = 2
    EventLatency = 3
)

// $BPF_CLANG_CFLAGS and $BPF_CFLAGS are set by the Makefile
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -cflags "-g -O2 -D__TARGET_ARCH_x86" -target amd64 probes ../probes/probes.bpf.c -- -I../probes

func main() {
    // Remove memlock limit — required for BPF maps on older kernels
    if err := rlimit.RemoveMemlock(); err != nil {
        log.Fatalf("remove memlock: %v", err)
    }

    // Load pre-compiled BPF object (generated by bpf2go)
    objs := probesObjects{}
    if err := loadProbesObjects(&objs, nil); err != nil {
        log.Fatalf("load BPF objects: %v", err)
    }
    defer objs.Close()

    // Attach tracepoint
    tpExecve, err := link.Tracepoint("syscalls", "sys_enter_execve", objs.TraceExecve, nil)
    if err != nil {
        log.Fatalf("attach execve tracepoint: %v", err)
    }
    defer tpExecve.Close()

    // Attach fentry (requires kernel >= 5.5, BTF present)
    feTcpConnect, err := link.AttachTracing(link.TracingOptions{
        Program: objs.TraceTcpConnect,
    })
    if err != nil {
        log.Fatalf("attach tcp_connect fentry: %v", err)
    }
    defer feTcpConnect.Close()

    // Open ring buffer reader
    rd, err := ringbuf.NewReader(objs.Events)
    if err != nil {
        log.Fatalf("open ring buffer: %v", err)
    }
    defer rd.Close()

    log.Println("collector running — ctrl+c to stop")

    // Graceful shutdown
    sig := make(chan os.Signal, 1)
    signal.Notify(sig, os.Interrupt)
    go func() {
        <-sig
        rd.Close()
    }()

    // Event loop
    var event Event
    for {
        record, err := rd.Read()
        if err != nil {
            if err == ringbuf.ErrClosed {
                return
            }
            log.Printf("ring buffer read error: %v", err)
            continue
        }

        if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &event); err != nil {
            log.Printf("decode error: %v", err)
            continue
        }

        route(&event)
    }
}

// route dispatches events to the right processor by type
func route(e *Event) {
    switch e.Type {
    case EventProcess:
        handleProcess(e)
    case EventConnect:
        handleConnect(e)
    case EventLatency:
        handleLatency(e)
    }
}

func handleProcess(e *Event) {
    comm     := nullStr(e.Comm[:])
    filename := nullStr(e.Filename[:])
    meta     := enrich(e.Pid)
    fmt.Printf("[EXEC] pid=%-6d comm=%-16s file=%s container=%s\n",
        e.Pid, comm, filename, meta.ContainerID)
    // TODO: emit as OTLP log record
}

func handleConnect(e *Event) {
    src  := net.IP(int32ToBytes(e.Saddr))
    dst  := net.IP(int32ToBytes(e.Daddr))
    meta := enrich(e.Pid)
    fmt.Printf("[CONN] pid=%-6d comm=%-16s %s:%d → %s:%d container=%s\n",
        e.Pid, nullStr(e.Comm[:]), src, e.Sport, dst, e.Dport, meta.ContainerID)
    // TODO: emit as OTLP span (trace TCP connection lifetime)
}

func handleLatency(e *Event) {
    src := net.IP(int32ToBytes(e.Saddr))
    dst := net.IP(int32ToBytes(e.Daddr))
    latencyMs := float64(e.LatencyNs) / 1_000_000.0
    fmt.Printf("[LAT]  pid=%-6d comm=%-16s %s:%d → %s:%d latency=%.3fms bytes=%d\n",
        e.Pid, nullStr(e.Comm[:]), src, e.Sport, dst, e.Dport, latencyMs, e.Bytes)
    // TODO: emit as OTLP histogram via MetricProcessor
}

// ProcMeta holds /proc-derived enrichment data
type ProcMeta struct {
    ContainerID string
    Cmdline     string
    CgroupPath  string
}

// enrich reads /proc/<pid>/cgroup to extract container ID
func enrich(pid uint32) ProcMeta {
    data, err := os.ReadFile(fmt.Sprintf("/proc/%d/cgroup", pid))
    if err != nil {
        return ProcMeta{}
    }
    // Container ID is typically the last 64-char hex segment of the cgroup path
    // Production: parse properly; this is illustrative
    return ProcMeta{CgroupPath: string(data)}
}

func nullStr(b []byte) string {
    n := bytes.IndexByte(b, 0)
    if n < 0 { return string(b) }
    return string(b[:n])
}

func int32ToBytes(n uint32) []byte {
    b := make([]byte, 4)
    binary.LittleEndian.PutUint32(b, n)
    return b
}
